nav:
  - 主页: 
    - index.md
    - 关于我: me.md
  - 开发工具:
    - Toolkit/index.md
    - Git: 
      - Toolkit/git/index.md
      - 01.Git起步: Toolkit/git/01.Git起步.md
      - 02.Git基础: Toolkit/git/02.Git基础.md
      - 03.远程仓库与分支: Toolkit/git/03.远程仓库与分支.md
      - git常用命令: Toolkit/git/git常用命令.md 
    - Vim:
      - Toolkit/vim/index.md
    

site_name: RichToo的垃圾堆

theme:
  name: material
  features:
    - navigation.tabs # 一级导航在横着的导航栏
    - content.code.annotate # 可以在代码块中增添点击展示的注释，参见 https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - navigation.tracking # 地址栏中的 URL 会随当前位置变化为对应小节的 URL
    - navigation.indexes # 将 index 页面直接附到小节名上
    - navigation.top # 回到顶部按钮
    - toc.follow # toc 跟随
  language: 'zh'
  palette:
    primary: cyan
    scheme: default
  font:
    text: Hiragino Sans GB # Palatino
    code: Roboto Mono

markdown_extensions:
  - md_in_html

