site_name: RichToo的垃圾堆
site_url: https://rich-too.github.io/My-Wiki/
repo_name: My-Wiki
repo_url: https://github.com/Rich-Too/My-Wiki

theme:
  name: material
  features:
    - navigation.tabs # 一级导航在横着的导航栏
    - content.code.annotate # 可以在代码块中增添点击展示的注释，参见 https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - navigation.tracking # 地址栏中的 URL 会随当前位置变化为对应小节的 URL
    - navigation.indexes # 将 index 页面直接附到小节名上
    - navigation.top # 回到顶部按钮
    - navigation.path # 页面上部添加导航 home->setup
    # - navigation.sections # 直接展开 没有箭头
    
    - toc.follow # toc 跟随
    # - toc.integrate # 相同栏左边加竖线

    - content.code.copy # 允许代码拷贝
    - content.code.annotate # 允许代码 annotations
    - content.tabs.link # 
    - content.tooltips # 鼠标移动到链接上显示，白条内容
    - content.code.select # render a button to allow for the selection of line ranges
  logo: assets/favicon.png
  favicon: assets/favicon.png
  language: 'zh'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: default
      accent: default
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true

  font: false
    # text: Noto Serif
    # code: Roboto Mono

markdown_extensions:
  - toc:
      permalink: true # link for each title
      slugify: !!python/name:pymdownx.slugs.uslugify # enable Unicode link
  - admonition
  - abbr
  - attr_list  # grid layout
  - md_in_html # 
  - def_list # flavors of lists 
  - footnotes # rendered at the bottom
  - tables # Data tables
  - meta
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.betterem:
  #     smart_enable: all
  - pymdownx.caret   #
  - pymdownx.critic  # apply specific formatting like highlight 
  - pymdownx.details #
  - pymdownx.emoji:  # emoji
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite

  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences: 
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - css/extra.css
  - css/font.css
  - css/heiti.css
  - https://fonts.loli.net/css2?family=Noto+Sans&family=PT+Sans&display=swap
  - https://fonts.loli.net/css?family=Open+Sans
  - https://fonts.loli.net/css?family=JetBrains+Mono
  - https://fonts.loli.net/css?family=Roboto+Mono
  - https://fonts.loli.net/css?family=Roboto
  - https://fonts.loli.net/css2?family=Source+Sans+Pro&display=swap 
  - https://cdnjs.cloudflare.com/ajax/libs/lxgw-wenkai-screen-webfont/1.7.0/style.css
  - https://cdn.jsdelivr.net/npm/hack-font@3/build/web/hack.css
  - https://fonts.loli.net/css?family=Fira+Sans
  - https://fonts.loli.net/css?family=PT+Sans

extra_javascript:
  # - js/mathjax.js # 支持数学公式，ref : https://squidfunk.github.io/mkdocs-material/reference/mathjax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # 支持表格排序
  # - js/tablesort.js
  - //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

plugins:
  - search:
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
  - glightbox # add image zoom functionality
  - statistics
nav:
  - 主页: 
    - index.md
    - 关于我: me.md
  - 开发工具:
    - Toolkit/index.md
    - Git: 
      - Toolkit/git/index.md
      - Git起步: Toolkit/git/01.Git起步.md
      - Git基础: Toolkit/git/02.Git基础.md
      - Git远程仓库与分支: Toolkit/git/03.远程仓库与分支.md
      - Git常用命令: Toolkit/git/git常用命令.md 
    - Vim: Toolkit/vim/vim.md
    - Shell: Toolkit/shell/Shell Tools and Scripting.md
  - 深度学习:
    - Tools:
      - DL/Tools/Math.md
      - DL/Tools/NumPy.md
      - DL/Tools/OS.md
      - DL/Tools/Pandas.md
      - DL/Tools/python.md